# Application
spring.application.name=cloverpit-backend

# DevTools
spring.devtools.restart.enabled=false

# Server
server.port=8080
server.servlet.context-path=/api

# MongoDB
spring.data.mongodb.uri=mongodb+srv://cloverpit:dlsghajtwlek@cloverpit.wwcuqqd.mongodb.net/CloverPit?retryWrites=true&w=majority&appName=CloverPit

# Security
spring.security.user.name=admin
spring.security.user.password=admin123

# JWT
jwt.secret=your-super-secret-jwt-key-change-this-in-production-min-256-bits-required-for-hs256-algorithm
jwt.expiration=86400000

# PUBG API
pubg.api-key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjMDU3NWNiMC1lYjBmLTAxM2UtYmFlMy01YWRhOTBkNzRiODgiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNzcwOTkwMTQ0LCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6ImNsb3ZlcnBpdCJ9.GWzjtTdfAClniRRjSxv5qERfKHbp-ElfuN324cJUlGo
pubg.platform=steam
pubg.shard=steam
pubg.base-url=https://api.pubg.com/shards

# Discord
discord.bot-token=
discord.guild-id=
discord.member-role-id=
discord.enabled=false
discord.webhook.url=https://discord.com/api/webhooks/1471003489822838899/e68g1FaDRri9HtgUPhniEGsWCPgs_4_3SdvqWdSdIY6Rkxs6Nc56hK_7R5W1Q_ep7LqG

# CORS
cors.allowed-origins=http://localhost:3000,https://your-frontend-domain.vercel.app

# Logging
logging.level.com.cloverpit=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
